<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>services score</name>
  <uuid>bc998f7d-9d40-4569-8b12-2babd911fa68</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the number of elements in the Services requested is more than 3
then
	add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
